substitutions:
  devicename: kogan_pow_1234
  name: Appliance
  hotspot: Appliance WiFi
  password: Password!
#  static_ip: 10.0.0.XX

  # Higher value gives lower watt readout
  current_res: '0.00087'
  # Lower value gives lower voltage readout
  voltage_div: '1980'

esphome:
  name: $devicename
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret ssid
  password: !secret psk
  fast_connect: on
#  manual_ip:
#    static_ip: $static_ip
#    gateway: 10.0.0.1
#    subnet: 255.255.255.0

  ap:
    ssid: $hotspot
    password: $password

captive_portal:

web_server:
  port: 80

logger:

api:
  password: !secret api_pwd

ota:
  password: !secret api_pwd

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $name IP Address

binary_sensor:
  - platform: status
    name: $name Status

  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    name: $name Button
    on_press:
      - switch.toggle: relay

switch:
- platform: gpio
  name: $name
  pin: GPIO14
  restore_mode: ALWAYS_OFF
  id: relay

- platform: gpio
  name: $name LED
  pin: GPIO13
  inverted: True
  restore_mode: ALWAYS_ON

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: $name WiFi Signal
    update_interval: 60s

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: $current_res
    voltage_divider: $voltage_div
    current:
      name: $name Amperage
      unit_of_measurement: A
    voltage:
      name: $name Voltage
      unit_of_measurement: V
    power:
      name: $name Wattage
      unit_of_measurement: W
      id: wattage
    change_mode_every: 8
    update_interval: 10s

  - platform: total_daily_energy
    name: $name Total Daily Energy
    power_id: wattage
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh

  - platform: uptime
    name: $name Uptime Sensor
